var dataDetailArr = [
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NRUYVRRBS075_VA_999?$thumbnail300$",
        name: "PUMA Men's Axelion Interest Stripe Crosstrainer",
        emiPrice: 12.99,
        price: 75.00,
        category: "Shoes",
        brand: "Puma",
        gender: "Male",
    },
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NRPB9NB3S130_VA_999?$thumbnail300$",
        name: "PUMA Men's Axelion LS Running Shoe",
        emiPrice: 12.99,
        price: 75.00,
        category: "Shoes",
        brand: "Puma" ,
        gender: "Male",
    },
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NRTK9NBLS090_VA_999?$thumbnail300$",
        name: "PUMA Men's Velocity 2.0 Low Composite-Toe Work Shoe",
        emiPrice: 18.99,
        price: 140.00,
        category: "Shoes",
        brand: "Puma",
        gender: "Male",
    },
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NRTLANBRS080_VA_999?$thumbnail300$",
        name: "PUMA Men's Conquest CTX High Waterproof Composite-Toe Work Boot",
        emiPrice: 18.99,
        price: 170.00,
        category: "Shoes",
        brand: "Puma",
        gender: "Male",
    },
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NRG09BLKS075_VA_999?$thumbnail300$",
        name: "PUMA Men's Pacer Future Trail Sneaker",
        emiPrice: 12.99,
        price: 75.00,
        category: "Shoes",
        brand: "Puma",
        gender: "Male",
    },
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NRIMFNBHS040_VA_999?$thumbnail300$",
        name: "PUMA Men's Twitch Runner Shoe",
        emiPrice: 12.99,
        price: 65.00,
        category: "Shoes",
        brand: "Puma",
        gender: "Male",
    },
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NQ8LENEKS070_VB_999?$thumbnail300$",
        name: "Puma Men's Cell Regulate Woven S Running Shoe",
        emiPrice: 12.99,
        price: 85.00,
        category: "Shoes",
        brand: "Puma",
        gender: "Male",
    },
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NRPBINAGS130_VA_999?$thumbnail300$",
        name: "PUMA Men's Rebound Rugged Sneaker Boot",
        emiPrice: 12.99,
        price: 75.00,
        category: "Shoes",
        brand: "Puma",
        gender: "Male",
    },
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NREPRNW4S085_VB_999?$thumbnail300$",
        name: "PUMA Men's Caven Basketball Shoe",
        emiPrice: 12.99,
        price: 60.00,
        category: "Shoes",
        brand: "Puma",
        gender: "Male",
    },
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NOLIKNGOS075_VA_999?$thumbnail300$",
        name: "PUMA Men's Cell Surin 2 Matte Running Shoe",
        emiPrice: 12.99,
        price: 80.00,
        category: "Shoes",
        brand: "Puma",
        gender: "Male",
    },
]



localStorage.setItem("procjectLstorage",JSON.stringify(dataDetailArr));