var dataDetailArr = [
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NRUYVRRBS075_VA_999?$thumbnail300$",
        name: "PUMA Men's Axelion Interest Stripe Crosstrainer",
        emiPrice: 12.99,
        price: 75.00,
        category: "Shoes",
        brand: "Puma",
        gender: "Male",
    },
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NRWYQAWGS090_VA_999?$thumbnail300$",
        name: "Reebok Men's Court Advance Sneaker",
        emiPrice: 12.99,
        price: 68.25,
        category: "Shoes",
        brand: "Reebook",
        gender: "Male",
    },
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NRPB9NB3S130_VA_999?$thumbnail300$",
        name: "PUMA Men's Axelion LS Running Shoe",
        emiPrice: 12.99,
        price: 75.00,
        category: "Shoes",
        brand: "Puma" ,
        gender: "Male",
    },
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NRTK9NBLS090_VA_999?$thumbnail300$",
        name: "PUMA Men's Velocity Composite-Toe Work Shoe",
        emiPrice: 18.99,
        price: 140.00,
        category: "Shoes",
        brand: "Puma",
        gender: "Male",
    },
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NRTLANBRS080_VA_999?$thumbnail300$",
        name: "PUMA Men's Conquest CTX High  Work Boot",
        emiPrice: 18.99,
        price: 170.00,
        category: "Shoes",
        brand: "Puma",
        gender: "Male",
    },
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NRG09BLKS075_VA_999?$thumbnail300$",
        name: "PUMA Men's Pacer Future Trail Sneaker",
        emiPrice: 12.99,
        price: 75.00,
        category: "Shoes",
        brand: "Puma",
        gender: "Male",
    },
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NRIMFNBHS040_VA_999?$thumbnail300$",
        name: "PUMA Men's Twitch Runner Shoe",
        emiPrice: 12.99,
        price: 65.00,
        category: "Shoes",
        brand: "Puma",
        gender: "Male",
    },
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NQ8LENEKS070_VB_999?$thumbnail300$",
        name: "Puma Men's Cell Regulate Woven S Running Shoe",
        emiPrice: 12.99,
        price: 85.00,
        category: "Shoes",
        brand: "Puma",
        gender: "Male",
    },
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NRPBINAGS130_VA_999?$thumbnail300$",
        name: "PUMA Men's Rebound Rugged Sneaker Boot",
        emiPrice: 12.99,
        price: 75.00,
        category: "Shoes",
        brand: "Puma",
        gender: "Male",
    },
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NREPRNW4S085_VB_999?$thumbnail300$",
        name: "PUMA Men's Caven Basketball Shoe",
        emiPrice: 12.99,
        price: 60.00,
        category: "Shoes",
        brand: "Puma",
        gender: "Male",
    },
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NOLIKNGOS075_VA_999?$thumbnail300$",
        name: "PUMA Men's Cell Surin 2 Matte Running Shoe",
        emiPrice: 12.99,
        price: 80.00,
        category: "Shoes",
        brand: "Puma",
        gender: "Male",
    },
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NRIG0NHEA2XL_VC_999?$thumbnail300$",
        name: "PUMA Women's PUMA Strong Training Tight",
        emiPrice: 11.99,
        price: 45.00,
        category: "Cloth",
        brand: "Puma",
        gender: "Female",
    },
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NRIG6NBLAXLG_VA_999?$thumbnail300$",
        name: "PUMA Women's PUMA Strong Woven Training Short",
        emiPrice: 9.99,
        price: 30.00,
        category: "Cloth",
        brand: "Puma",
        gender: "Female",
    },
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NQUS4REDA3XL_VD_999?$thumbnail300$",
        name: "PUMA Men's Big/Tall Essentials Cat Logo Tee",
        emiPrice: 9.99,
        price: 25.00,
        category: "Cloth",
        brand: "Puma",
        gender: "Male",
    },
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NQUJGROWA2XL_VC_999?$thumbnail300$",
        name: "PUMA Women's Essentials Logo Tee",
        emiPrice: 9.99,
        price: 25.00,
        category: "Cloth",
        brand: "Puma",
        gender: "Female",
    },
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NRFOTANWA2XL_VC_999?$thumbnail300$",
        name: "PUMA Men's Big/Tall Contrast Track Pant 2.0",
        emiPrice: 11.99,
        price: 40.00,
        category: "Cloth",
        brand: "Puma",
        gender: "Male",
    },
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NRXK4VOCAXLG_VA_999?$thumbnail300$",
        name: "PUMA Women's Essentials+ Frozen Flower Print Legging",
        emiPrice: 11.99,
        price: 40.00,
        category: "Cloth",
        brand: "Puma",
        gender: "Female",
    },
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NRPBJLGHMNGL_VA_999?$thumbnail300$",
        name: "PUMA Women's Essentials Logo Bike Short",
        emiPrice: 9.99,
        price: 25.00,
        category: "Cloth",
        brand: "Puma",
        gender: "Female",
    },
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NRFOPNBHA3XL_VA_999?$thumbnail300$",
        name: "PUMA Women's Essentials Sweatpant",
        emiPrice: 11.99,
        price: 45.00,
        category: "Cloth",
        brand: "Puma",
        gender: "Female",
    },
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NPF4VNB3AXLG_VA_999?$thumbnail300$",
        name: "PUMA Men's Speed Pant",
        emiPrice: 11.99,
        price: 45.00,
        category: "Cloth",
        brand: "Puma",
        gender: "Male",
    },
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NRWZ2AWBS085_VA_999?$thumbnail300$",
        name: "Reebok Women's Glide Running Shoe",
        emiPrice: 12.99,
        price: 73.50,
        category: "Shoes",
        brand: "Reebook",
        gender: "Female",
    },
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NQ7NKNWHS060_VA_999?$thumbnail300$",
        name: "Reebok Women's BB4500 Hi Basketball-Style Sneaker",
        emiPrice: 12.99,
        price: 68.25,
        category: "Shoes",
        brand: "Reebook",
        gender: "Female",
    }, 
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NRE24VBGA2XL_VA_999?$thumbnail300$",
        name: "Reebok Men's Identity Big Logo Tee",
        emiPrice: 9.99,
        price: 27.50,
        category: "Cloth",
        brand: "Reebook",
        gender: "Male",
    }, 
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NRFKFMGHAXLG_VA_999?$thumbnail300$",
        name: "Reebok Women's Identity Big Logo Fleece Pant",
        emiPrice: 11.99,
        price: 55.00,
        category: "Cloth",
        brand: "Reebook",
        gender: "Female",
    }, 
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NRWFRKBYS110_VA_999?$thumbnail300$",
        name: "New Balance Women's 574 Sneaker",
        emiPrice: 14.99,
        price: 84.99,
        category: "Shoes",
        brand: "New Balance",
        gender: "Female",
    }, 
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NQ8GFNBLS075_VC_999?$thumbnail300$",
        name: "New Balance Men's Fresh Foam 680v7 Running Shoe",
        emiPrice: 12.99,
        price: 79.99,
        category: "Shoes",
        brand: "New Balance",
        gender: "Male",
    }, 
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NRWPFAYRS130_VA_999?$thumbnail300$",
        name: "New Balance Men's 515v3 Sneaker",
        emiPrice: 12.99,
        price: 74.99,
        category: "Shoes",
        brand: "New Balance",
        gender: "Male",
    }, 
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NRIUKNQWS060_VA_999?$thumbnail300$",
        name: "New Balance Women's DynaSoft Running Shoe",
        emiPrice: 12.99,
        price: 64.99,
        category: "Shoes",
        brand: "New Balance",
        gender: "Female",
    }, 
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NQ1WUAYRS075_VA_999?$thumbnail300$",
        name: "New Balance Men's 520v7 Running Shoe",
        emiPrice: 12.99,
        price: 64.99,
        category: "Shoes",
        brand: "New Balance",
        gender: "Male",
    }, 
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NR2OK0000010_VA_999?$thumbnail300$",
        name: "Apple iPhone 14 Pro Max 6.7 128GB Unlocked iOS ",
        emiPrice: 73.90,
        price: 1459.99,
        category: "Electronics",
        brand: "Apple",
        gender: "",
    },
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NRWWS0000010_VA_999?$thumbnail300$",
        name: "Samsung Galaxy A23 6.6 Full HD+ 64GB Unlocked ",
        emiPrice: 24.99,
        price: 269.99,
        category: "Electronics",
        brand: "Samsung",
        gender: "",
    },
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NRSHJNBL0010_VA_999?$thumbnail300$",
        name: "Samsung Galaxy S22 Ultra 5G 6.8 256GB Unlocked",
        emiPrice: 73.99,
        price: 1459.99,
        category: "Electronics",
        brand: "Samsung",
        gender: "",
    },
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NR2OM0000010_VA_999?$thumbnail300$",
        name: "Apple iPhone 14 6.1 128GB Unlocked iOS Smartphone ",
        emiPrice: 59.99,
        price: 1059.99,
        category: "Electronics",
        brand: "Apple",
        gender: "",
    },
    {
        img_url: "https://s7d5.scene7.com/is/image/bluestembrands/4NRABG0000010_VA_999?$thumbnail300$",
        name: "Samsung Mobile F4L 2.8 4GB Unlocked Flip Phone",
        emiPrice: 18.99,
        price: 114.99,
        category: "Electronics",
        brand: "Samsung",
        gender: "",
    },
    // {
    //     img_url: ,
    //     name: ,
    //     emiPrice: ,
    //     price: ,
    //     category: ,
    //     brand: ,
    //     gender: ,
    // },
    // {
    //     img_url: ,
    //     name: ,
    //     emiPrice: ,
    //     price: ,
    //     category: ,
    //     brand: ,
    //     gender: ,
    // },
    // {
    //     img_url: ,
    //     name: ,
    //     emiPrice: ,
    //     price: ,
    //     category: ,
    //     brand: ,
    //     gender: ,
    // },
    // {
    //     img_url: ,
    //     name: ,
    //     emiPrice: ,
    //     price: ,
    //     category: ,
    //     brand: ,
    //     gender: ,
    // },
    // {
    //     img_url: ,
    //     name: ,
    //     emiPrice: ,
    //     price: ,
    //     category: ,
    //     brand: ,
    //     gender: ,
    // },
]



localStorage.setItem("procjectLstorage",JSON.stringify(dataDetailArr));